# Generated by Django 5.2.7 on 2025-10-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="मुख्य शीर्षक, जैसे 'Crafted Stones For Your Space'", max_length=200)),
                ('subtitle', models.TextField(help_text='शीर्षक के नीचे का पैराग्राफ')),
                ('button_text', models.CharField(default='Browse Products', help_text='पहले बटन का टेक्स्ट', max_length=50)),
                ('button_link', models.CharField(default='/products/', help_text='पहले बटन का लिंक (जैसे /products/ या #categories)', max_length=200)),
                ('secondary_button_text', models.CharField(default='Our Categories', help_text='दूसरे बटन का टेक्स्ट', max_length=50)),
                ('secondary_button_link', models.CharField(default='#categories', help_text='दूसरे बटन का लिंक', max_length=200)),
                ('image', models.ImageField(help_text='हीरो सेक्शन में दिखने वाली इमेज', upload_to='hero_images/')),
                ('is_active', models.BooleanField(default=True, help_text='क्या यह हीरो सेक्शन अभी वेबसाइट पर लाइव है?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-created_at'],
            },
        ),
    ]
