# Generated by Django 5.2.7 on 2025-10-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='video',
            field=models.FileField(blank=True, help_text='hero section video', null=True, upload_to='hero_videos/'),
        ),
    ]
