# Generated by Django 5.2.7 on 2025-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
