# Generated by Django 5.2.7 on 2025-10-20 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('price', models.CharField(max_length=50)),
                ('Order_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(blank=True, null=True)),
                ('height', models.CharField(blank=True, null=True)),
                ('usage_application', models.CharField(blank=True, null=True)),
                ('model_number', models.CharField()),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('production_capacity', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=200, null=True)),
                ('packaging_details', models.CharField(blank=True, max_length=200, null=True)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('material', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('dimensions', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ('-is_featured', '-created_at', 'name'),
            },
        ),
    ]
