# Generated by Django 5.2.7 on 2025-12-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/gallery/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(max_length=1000),
        ),
    ]
